/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-07-06 07:13:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Title  -->\r\n");
      out.write("    <title>Amado - Furniture Ecommerce Template | Shop</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon  -->\r\n");
      out.write("    <link rel=\"icon\" href=\"resources/amado/img/core-img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Core Style CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/amado/css/core-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/amado/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Search Wrapper Area Start -->\r\n");
      out.write("    <div class=\"search-wrapper section-padding-100\">\r\n");
      out.write("        <div class=\"search-close\">\r\n");
      out.write("            <i class=\"fa fa-close\" aria-hidden=\"true\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"search-content\">\r\n");
      out.write("                        <form action=\"#\" method=\"get\">\r\n");
      out.write("                            <input type=\"search\" name=\"search\" id=\"search\" placeholder=\"Type your keyword...\">\r\n");
      out.write("                            <button type=\"submit\"><img src=\"resources/amado/img/core-img/search.png\" alt=\"\"></button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Search Wrapper Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Main Content Wrapper Start ##### -->\r\n");
      out.write("    <div class=\"main-content-wrapper d-flex clearfix\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Nav (max width 767px)-->\r\n");
      out.write("        <div class=\"mobile-nav\">\r\n");
      out.write("            <!-- Navbar Brand -->\r\n");
      out.write("            <div class=\"amado-navbar-brand\">\r\n");
      out.write("                <a href=\"index.do\"><img src=\"resources/amado/img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Navbar Toggler -->\r\n");
      out.write("            <div class=\"amado-navbar-toggler\">\r\n");
      out.write("                <span></span><span></span><span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Header Area Start -->\r\n");
      out.write("        <header class=\"header-area clearfix\">\r\n");
      out.write("            <!-- Close Icon -->\r\n");
      out.write("            <div class=\"nav-close\">\r\n");
      out.write("                <i class=\"fa fa-close\" aria-hidden=\"true\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"index.do\"><img src=\"resources/amado/img/core-img/logo.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Amado Nav -->\r\n");
      out.write("            <nav class=\"amado-nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"index.do\">Home</a></li>\r\n");
      out.write("                    <li class=\"active\"><a href=\"shop.do\">Shop</a></li>\r\n");
      out.write("                    <li><a href=\"product-details.do\">Product</a></li>\r\n");
      out.write("                    <li><a href=\"cart.do\">Cart</a></li>\r\n");
      out.write("                    <li><a href=\"checkout.do\">Checkout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- Button Group -->\r\n");
      out.write("            <div class=\"amado-btn-group mt-30 mb-100\">\r\n");
      out.write("                <a href=\"#\" class=\"btn amado-btn mb-15\">%Discount%</a>\r\n");
      out.write("                <a href=\"#\" class=\"btn amado-btn active\">New this week</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Cart Menu -->\r\n");
      out.write("            <div class=\"cart-fav-search mb-100\">\r\n");
      out.write("                <a href=\"cart.do\" class=\"cart-nav\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"> Cart <span>(0)</span></a>\r\n");
      out.write("                <a href=\"#\" class=\"fav-nav\"><img src=\"resources/amado/img/core-img/favorites.png\" alt=\"\"> Favourite</a>\r\n");
      out.write("                <a href=\"#\" class=\"search-nav\"><img src=\"resources/amado/img/core-img/search.png\" alt=\"\"> Search</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Social Button -->\r\n");
      out.write("            <div class=\"social-info d-flex justify-content-between\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- Header Area End -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"shop_sidebar_area\">\r\n");
      out.write("\r\n");
      out.write("            <!-- ##### Single Widget ##### -->\r\n");
      out.write("            <div class=\"widget catagory mb-50\">\r\n");
      out.write("                <!-- Widget Title -->\r\n");
      out.write("                <h6 class=\"widget-title mb-30\">Catagories</h6>\r\n");
      out.write("\r\n");
      out.write("                <!--  Catagories  -->\r\n");
      out.write("                <div class=\"catagories-menu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"active\"><a href=\"#\">Chairs</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Beds</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Accesories</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Furniture</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Home Deco</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Dressings</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Tables</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ##### Single Widget ##### -->\r\n");
      out.write("            <div class=\"widget brands mb-50\">\r\n");
      out.write("                <!-- Widget Title -->\r\n");
      out.write("                <h6 class=\"widget-title mb-30\">Brands</h6>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"widget-desc\">\r\n");
      out.write("                    <!-- Single Form Check -->\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"amado\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"amado\">Amado</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Form Check -->\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"ikea\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"ikea\">Ikea</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Form Check -->\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"furniture\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"furniture\">Furniture Inc</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Form Check -->\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"factory\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"factory\">The factory</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Single Form Check -->\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"artdeco\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"artdeco\">Artdeco</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ##### Single Widget ##### -->\r\n");
      out.write("            <div class=\"widget color mb-50\">\r\n");
      out.write("                <!-- Widget Title -->\r\n");
      out.write("                <h6 class=\"widget-title mb-30\">Color</h6>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"widget-desc\">\r\n");
      out.write("                    <ul class=\"d-flex\">\r\n");
      out.write("                        <li><a href=\"#\" class=\"color1\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color2\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color3\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color4\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color5\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color6\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color7\"></a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"color8\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ##### Single Widget ##### -->\r\n");
      out.write("            <div class=\"widget price mb-50\">\r\n");
      out.write("                <!-- Widget Title -->\r\n");
      out.write("                <h6 class=\"widget-title mb-30\">Price</h6>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"widget-desc\">\r\n");
      out.write("                    <div class=\"slider-range\">\r\n");
      out.write("                        <div data-min=\"10\" data-max=\"1000\" data-unit=\"$\" class=\"slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all\" data-value-min=\"10\" data-value-max=\"1000\" data-label-result=\"\">\r\n");
      out.write("                            <div class=\"ui-slider-range ui-widget-header ui-corner-all\"></div>\r\n");
      out.write("                            <span class=\"ui-slider-handle ui-state-default ui-corner-all\" tabindex=\"0\"></span>\r\n");
      out.write("                            <span class=\"ui-slider-handle ui-state-default ui-corner-all\" tabindex=\"0\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"range-price\">$10 - $1000</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"amado_product_area section-padding-100\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"product-topbar d-xl-flex align-items-end justify-content-between\">\r\n");
      out.write("                            <!-- Total Products -->\r\n");
      out.write("                            <div class=\"total-products\">\r\n");
      out.write("                                <p>Showing 1-8 0f 25</p>\r\n");
      out.write("                                <div class=\"view d-flex\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-th-large\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-bars\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Sorting -->\r\n");
      out.write("                            <div class=\"product-sorting d-flex\">\r\n");
      out.write("                                <div class=\"sort-by-date d-flex align-items-center mr-15\">\r\n");
      out.write("                                    <p>Sort by</p>\r\n");
      out.write("                                    <form action=\"#\" method=\"get\">\r\n");
      out.write("                                        <select name=\"select\" id=\"sortBydate\">\r\n");
      out.write("                                            <option value=\"value\">Date</option>\r\n");
      out.write("                                            <option value=\"value\">Newest</option>\r\n");
      out.write("                                            <option value=\"value\">Popular</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"view-product d-flex align-items-center\">\r\n");
      out.write("                                    <p>View</p>\r\n");
      out.write("                                    <form action=\"#\" method=\"get\">\r\n");
      out.write("                                        <select name=\"select\" id=\"viewProduct\">\r\n");
      out.write("                                            <option value=\"value\">12</option>\r\n");
      out.write("                                            <option value=\"value\">24</option>\r\n");
      out.write("                                            <option value=\"value\">48</option>\r\n");
      out.write("                                            <option value=\"value\">96</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product1.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product2.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product2.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product3.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                          s  <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product3.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product4.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product4.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product5.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product5.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product6.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Single Product Area -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-6 col-md-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"single-product-wrapper\">\r\n");
      out.write("                            <!-- Product Image -->\r\n");
      out.write("                            <div class=\"product-img\">\r\n");
      out.write("                                <img src=\"resources/amado/img/product-img/product6.jpg\" alt=\"\">\r\n");
      out.write("                                <!-- Hover Thumb -->\r\n");
      out.write("                                <img class=\"hover-img\" src=\"resources/amado/img/product-img/product1.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Product Description -->\r\n");
      out.write("                            <div class=\"product-description d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                <!-- Product Meta Data -->\r\n");
      out.write("                                <div class=\"product-meta-data\">\r\n");
      out.write("                                    <div class=\"line\"></div>\r\n");
      out.write("                                    <p class=\"product-price\">$180</p>\r\n");
      out.write("                                    <a href=\"product-details.do\">\r\n");
      out.write("                                        <h6>Modern Chair</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Ratings & Cart -->\r\n");
      out.write("                                <div class=\"ratings-cart text-right\">\r\n");
      out.write("                                    <div class=\"ratings\">\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cart\">\r\n");
      out.write("                                        <a href=\"cart.do\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to Cart\"><img src=\"resources/amado/img/core-img/cart.png\" alt=\"\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <!-- Pagination -->\r\n");
      out.write("                        <nav aria-label=\"navigation\">\r\n");
      out.write("                            <ul class=\"pagination justify-content-end mt-50\">\r\n");
      out.write("                                <li class=\"page-item active\"><a class=\"page-link\" href=\"#\">01.</a></li>\r\n");
      out.write("                                <li class=\"page-item\"><a class=\"page-link\" href=\"#\">02.</a></li>\r\n");
      out.write("                                <li class=\"page-item\"><a class=\"page-link\" href=\"#\">03.</a></li>\r\n");
      out.write("                                <li class=\"page-item\"><a class=\"page-link\" href=\"#\">04.</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ##### Main Content Wrapper End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Newsletter Area Start ##### -->\r\n");
      out.write("    <section class=\"newsletter-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <!-- Newsletter Text -->\r\n");
      out.write("                <div class=\"col-12 col-lg-6 col-xl-7\">\r\n");
      out.write("                    <div class=\"newsletter-text mb-100\">\r\n");
      out.write("                        <h2>Subscribe for a <span>25% Discount</span></h2>\r\n");
      out.write("                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Newsletter Form -->\r\n");
      out.write("                <div class=\"col-12 col-lg-6 col-xl-5\">\r\n");
      out.write("                    <div class=\"newsletter-form mb-100\">\r\n");
      out.write("                        <form action=\"#\" method=\"post\">\r\n");
      out.write("                            <input type=\"email\" name=\"email\" class=\"nl-email\" placeholder=\"Your E-mail\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Subscribe\">\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ##### Newsletter Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("    <footer class=\"footer_area clearfix\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <!-- Single Widget Area -->\r\n");
      out.write("                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"single_widget_area\">\r\n");
      out.write("                        <!-- Logo -->\r\n");
      out.write("                        <div class=\"footer-logo mr-50\">\r\n");
      out.write("                            <a href=\"index.do\"><img src=\"resources/amado/img/core-img/logo2.png\" alt=\"\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Copywrite Text -->\r\n");
      out.write("                        <p class=\"copywrite\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Single Widget Area -->\r\n");
      out.write("                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                    <div class=\"single_widget_area\">\r\n");
      out.write("                        <!-- Footer Menu -->\r\n");
      out.write("                        <div class=\"footer_menu\">\r\n");
      out.write("                            <nav class=\"navbar navbar-expand-lg justify-content-end\">\r\n");
      out.write("                                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#footerNavContent\" aria-controls=\"footerNavContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><i class=\"fa fa-bars\"></i></button>\r\n");
      out.write("                                <div class=\"collapse navbar-collapse\" id=\"footerNavContent\">\r\n");
      out.write("                                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                                        <li class=\"nav-item active\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"index.do\">Home</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"shop.do\">Shop</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"product-details.do\">Product</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"cart.do\">Cart</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"checkout.do\">Checkout</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ##### Footer Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->\r\n");
      out.write("    <script src=\"resources/amado/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"resources/amado/js/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <script src=\"resources/amado/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Plugins js -->\r\n");
      out.write("    <script src=\"resources/amado/js/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"resources/amado/js/active.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
